# Change these first
owner: presswizards # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Press Wizards Main Site
    url: https://presswizards.com
  - name: Billing System
    url: https://billing.presswizards.com
  - name: Web Server 4
    url: https://plesk.presswizards.com
  - name: Web Server 5
    url: https://plesk.presswizards.com
  - name: Web Server 1
    url: https://web1.yourserver.net
  - name: Web Server 2
    url: https://web2.yourserver.net
  - name: Web Server 3
    url: https://web3.yourserver.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: upptime.presswizards.com
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Press Wizards **Upptime** open source monitoring system"
  introMessage: Web Server Status for Press Wizards. No server required — powered by GitHub [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: PressWizards.com
      href: https://presswizards.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
